AWSTemplateFormatVersion: '2010-09-09'
Description: 'TRACE - IAM Roles and Policies'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]

Resources:
  # ===========================================
  # Lambda Execution Role
  # ===========================================
  TRACELambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'TRACE-Lambda-Role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TRACELambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # DynamoDB Access
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TRACE-*'
              # Kinesis Access
              - Effect: Allow
                Action:
                  - kinesis:GetRecords
                  - kinesis:GetShardIterator
                  - kinesis:DescribeStream
                  - kinesis:ListStreams
                  - kinesis:PutRecord
                  - kinesis:PutRecords
                Resource: !Sub 'arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/TRACE-*'
              # S3 Access
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::trace-telemetry-${AWS::AccountId}/*'
                  - !Sub 'arn:aws:s3:::trace-telemetry-${AWS::AccountId}'
              # Timestream Access
              - Effect: Allow
                Action:
                  - timestream:WriteRecords
                  - timestream:DescribeEndpoints
                  - timestream:Select
                Resource: '*'
              # SageMaker Invoke
              - Effect: Allow
                Action:
                  - sagemaker:InvokeEndpoint
                Resource: !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:endpoint/TRACE-*'
              # CloudWatch
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - cloudwatch:GetMetricData
                Resource: '*'

  # ===========================================
  # Bedrock Agent Role
  # ===========================================
  TRACEBedrockAgentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'TRACE-Bedrock-Agent-Role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TRACEBedrockAgentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Invoke Bedrock Models
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/*'
              # Invoke Lambda Tools
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:TRACE-*'
              # Knowledge Base Access
              - Effect: Allow
                Action:
                  - bedrock:Retrieve
                  - bedrock:RetrieveAndGenerate
                Resource: !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:knowledge-base/*'
              # S3 for Knowledge Base
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::trace-knowledge-base-${AWS::AccountId}/*'
                  - !Sub 'arn:aws:s3:::trace-knowledge-base-${AWS::AccountId}'
              # Agent Collaboration
              - Effect: Allow
                Action:
                  - bedrock:InvokeAgent
                Resource: !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent/*'

  # ===========================================
  # SageMaker Execution Role
  # ===========================================
  TRACESageMakerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'TRACE-SageMaker-Role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Policies:
        - PolicyName: TRACESageMakerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::trace-models-${AWS::AccountId}/*'
                  - !Sub 'arn:aws:s3:::trace-models-${AWS::AccountId}'

  # ===========================================
  # Step Functions Role
  # ===========================================
  TRACEStepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'TRACE-StepFunctions-Role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TRACEStepFunctionsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:TRACE-*'
              - Effect: Allow
                Action:
                  - bedrock:InvokeAgent
                Resource: !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent/*'
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:TRACE-*'

  # ===========================================
  # API Gateway Role
  # ===========================================
  TRACEAPIGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'TRACE-APIGateway-Role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TRACEAPIGatewayPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:TRACE-*'

Outputs:
  LambdaRoleArn:
    Description: Lambda Execution Role ARN
    Value: !GetAtt TRACELambdaExecutionRole.Arn
    Export:
      Name: !Sub 'TRACE-Lambda-Role-Arn-${Environment}'

  BedrockAgentRoleArn:
    Description: Bedrock Agent Role ARN
    Value: !GetAtt TRACEBedrockAgentRole.Arn
    Export:
      Name: !Sub 'TRACE-Bedrock-Agent-Role-Arn-${Environment}'

  SageMakerRoleArn:
    Description: SageMaker Role ARN
    Value: !GetAtt TRACESageMakerRole.Arn
    Export:
      Name: !Sub 'TRACE-SageMaker-Role-Arn-${Environment}'

  StepFunctionsRoleArn:
    Description: Step Functions Role ARN
    Value: !GetAtt TRACEStepFunctionsRole.Arn
    Export:
      Name: !Sub 'TRACE-StepFunctions-Role-Arn-${Environment}'
