AWSTemplateFormatVersion: '2010-09-09'
Description: 'TRACE - Kinesis Data Streams'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]

Resources:
  # ===========================================
  # Main Telemetry Stream
  # ===========================================
  TelemetryStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub 'TRACE-TowerTelemetry-${Environment}'
      ShardCount: 2
      RetentionPeriodHours: 24
      StreamEncryption:
        EncryptionType: KMS
        KeyId: alias/aws/kinesis
      Tags:
        - Key: Project
          Value: TRACE
        - Key: Environment
          Value: !Ref Environment

  # ===========================================
  # Agent Events Stream
  # ===========================================
  AgentEventsStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub 'TRACE-AgentEvents-${Environment}'
      ShardCount: 1
      RetentionPeriodHours: 24
      StreamEncryption:
        EncryptionType: KMS
        KeyId: alias/aws/kinesis
      Tags:
        - Key: Project
          Value: TRACE
        - Key: Environment
          Value: !Ref Environment

  # ===========================================
  # Remediation Events Stream
  # ===========================================
  RemediationStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub 'TRACE-RemediationEvents-${Environment}'
      ShardCount: 1
      RetentionPeriodHours: 168  # 7 days for audit
      StreamEncryption:
        EncryptionType: KMS
        KeyId: alias/aws/kinesis
      Tags:
        - Key: Project
          Value: TRACE
        - Key: Environment
          Value: !Ref Environment

Outputs:
  TelemetryStreamArn:
    Description: Telemetry Stream ARN
    Value: !GetAtt TelemetryStream.Arn
    Export:
      Name: !Sub 'TRACE-TelemetryStream-Arn-${Environment}'

  TelemetryStreamName:
    Description: Telemetry Stream Name
    Value: !Ref TelemetryStream
    Export:
      Name: !Sub 'TRACE-TelemetryStream-Name-${Environment}'

  AgentEventsStreamArn:
    Description: Agent Events Stream ARN
    Value: !GetAtt AgentEventsStream.Arn
    Export:
      Name: !Sub 'TRACE-AgentEventsStream-Arn-${Environment}'

  RemediationStreamArn:
    Description: Remediation Stream ARN
    Value: !GetAtt RemediationStream.Arn
    Export:
      Name: !Sub 'TRACE-RemediationStream-Arn-${Environment}'
