#!/usr/bin/env python3
"""
TRACE Frontend Deployment Script

Deploys the React dashboard to S3 with CloudFront.
"""

import boto3
import json
import os
import subprocess
from pathlib import Path

# Configuration
ENVIRONMENT = os.getenv('TRACE_ENV', 'dev')
REGION = os.getenv('AWS_REGION', 'us-east-1')

# Initialize clients
s3_client = boto3.client('s3', region_name=REGION)
cloudfront_client = boto3.client('cloudfront', region_name=REGION)
sts_client = boto3.client('sts', region_name=REGION)

def get_account_id():
    return sts_client.get_caller_identity()['Account']

def load_api_outputs():
    """Load API outputs from previous deployment"""
    output_file = Path(__file__).parent.parent / 'api-outputs.json'
    if output_file.exists():
        with open(output_file, 'r') as f:
            return json.load(f)
    return {}


def update_frontend_config():
    """Update frontend configuration with API URL"""
    
    print("  Updating frontend configuration...")
    
    api_outputs = load_api_outputs()
    api_url = api_outputs.get('rest_api', {}).get('api_url', 'http://localhost:8000')
    
    # Path to client directory
    client_dir = Path(__file__).parent.parent.parent / 'client'
    
    if not client_dir.exists():
        print(f"    ⚠️ Client directory not found: {client_dir}")
        return False
    
    # Create .env file
    env_content = f"""# TRACE Frontend Configuration
# Generated by deploy-frontend.py

VITE_API_URL={api_url}
VITE_WS_URL={api_url.replace('https://', 'wss://').replace('http://', 'ws://')}
VITE_ENVIRONMENT={ENVIRONMENT}
"""
    
    env_file = client_dir / '.env'
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    print(f"    Created .env with API_URL: {api_url}")
    return True


def build_frontend():
    """Build the frontend application"""
    
    print("\n  Building frontend...")
    
    client_dir = Path(__file__).parent.parent.parent / 'client'
    
    if not client_dir.exists():
        print(f"    ⚠️ Client directory not found: {client_dir}")
        return None
    
    # Check if node_modules exists
    node_modules = client_dir / 'node_modules'
    if not node_modules.exists():
        print("    Installing dependencies...")
        subprocess.run(['npm', 'install'], cwd=client_dir, check=True)
    
    # Build
    print("    Running build...")
    subprocess.run(['npm', 'run', 'build'], cwd=client_dir, check=True)
    
    dist_dir = client_dir / 'dist'
    if dist_dir.exists():
        print(f"    ✅ Build successful: {dist_dir}")
        return dist_dir
    else:
        print("    ❌ Build failed - dist directory not found")
        return None


def upload_to_s3(dist_dir: Path):
    """Upload built files to S3"""
    
    print("\n  Uploading to S3...")
    
    account_id = get_account_id()
    bucket_name = f'trace-frontend-{account_id}-{ENVIRONMENT}'
    
    # Check if bucket exists
    try:
        s3_client.head_bucket(Bucket=bucket_name)
        print(f"    Bucket exists: {bucket_name}")
    except:
        print(f"    Bucket not found: {bucket_name}")
        print("    Run 01-infrastructure/setup-infrastructure.py first")
        return None
    
    # Upload files
    file_count = 0
    for file_path in dist_dir.rglob('*'):
        if file_path.is_file():
            relative_path = file_path.relative_to(dist_dir)
            s3_key = str(relative_path)
            
            # Determine content type
            content_type = 'application/octet-stream'
            if file_path.suffix == '.html':
                content_type = 'text/html'
            elif file_path.suffix == '.js':
                content_type = 'application/javascript'
            elif file_path.suffix == '.css':
                content_type = 'text/css'
            elif file_path.suffix == '.json':
                content_type = 'application/json'
            elif file_path.suffix == '.svg':
                content_type = 'image/svg+xml'
            elif file_path.suffix == '.png':
                content_type = 'image/png'
            elif file_path.suffix == '.ico':
                content_type = 'image/x-icon'
            
            s3_client.upload_file(
                str(file_path),
                bucket_name,
                s3_key,
                ExtraArgs={'ContentType': content_type}
            )
            file_count += 1
    
    print(f"    Uploaded {file_count} files")
    
    # Get website URL
    website_url = f'http://{bucket_name}.s3-website-{REGION}.amazonaws.com'
    
    return {
        'bucket': bucket_name,
        'url': website_url,
        'files_uploaded': file_count
    }


def create_cloudfront_distribution(bucket_name: str):
    """Create CloudFront distribution for the S3 bucket"""
    
    print("\n  Setting up CloudFront...")
    
    # Check for existing distribution
    distributions = cloudfront_client.list_distributions()
    existing_dist = None
    
    if 'DistributionList' in distributions and 'Items' in distributions['DistributionList']:
        for dist in distributions['DistributionList']['Items']:
            for origin in dist['Origins']['Items']:
                if bucket_name in origin.get('DomainName', ''):
                    existing_dist = dist
                    break
    
    if existing_dist:
        print(f"    Found existing distribution: {existing_dist['Id']}")
        return {
            'distribution_id': existing_dist['Id'],
            'domain_name': existing_dist['DomainName'],
            'url': f"https://{existing_dist['DomainName']}"
        }
    
    # Create new distribution
    print("    Creating new CloudFront distribution...")
    
    origin_id = f'{bucket_name}-origin'
    
    try:
        response = cloudfront_client.create_distribution(
            DistributionConfig={
                'CallerReference': f'trace-{bucket_name}',
                'Comment': f'TRACE Dashboard - {ENVIRONMENT}',
                'Enabled': True,
                'Origins': {
                    'Quantity': 1,
                    'Items': [
                        {
                            'Id': origin_id,
                            'DomainName': f'{bucket_name}.s3-website-{REGION}.amazonaws.com',
                            'CustomOriginConfig': {
                                'HTTPPort': 80,
                                'HTTPSPort': 443,
                                'OriginProtocolPolicy': 'http-only'
                            }
                        }
                    ]
                },
                'DefaultCacheBehavior': {
                    'TargetOriginId': origin_id,
                    'ViewerProtocolPolicy': 'redirect-to-https',
                    'TrustedSigners': {'Enabled': False, 'Quantity': 0},
                    'ForwardedValues': {
                        'QueryString': False,
                        'Cookies': {'Forward': 'none'}
                    },
                    'MinTTL': 0,
                    'DefaultTTL': 86400,
                    'MaxTTL': 31536000
                },
                'DefaultRootObject': 'index.html',
                'CustomErrorResponses': {
                    'Quantity': 1,
                    'Items': [
                        {
                            'ErrorCode': 404,
                            'ResponsePagePath': '/index.html',
                            'ResponseCode': '200',
                            'ErrorCachingMinTTL': 300
                        }
                    ]
                }
            }
        )
        
        dist_info = response['Distribution']
        print(f"    Created distribution: {dist_info['Id']}")
        print(f"    Domain: {dist_info['DomainName']}")
        print("    ⚠️ Note: CloudFront may take 15-20 minutes to deploy globally")
        
        return {
            'distribution_id': dist_info['Id'],
            'domain_name': dist_info['DomainName'],
            'url': f"https://{dist_info['DomainName']}"
        }
        
    except Exception as e:
        print(f"    Error creating CloudFront: {str(e)}")
        return None


def main():
    print("=" * 60)
    print("TRACE Frontend Deployment")
    print("=" * 60)
    print(f"Environment: {ENVIRONMENT}")
    print(f"Region: {REGION}")
    print()
    
    # Step 1: Update configuration
    print("📝 Step 1: Updating configuration...")
    update_frontend_config()
    
    # Step 2: Build frontend
    print("\n🔨 Step 2: Building frontend...")
    dist_dir = build_frontend()
    
    if not dist_dir:
        print("\n⚠️ Frontend build skipped or failed")
        print("You can manually build and deploy:")
        print("  1. cd client && npm install && npm run build")
        print("  2. aws s3 sync dist/ s3://trace-frontend-ACCOUNT-dev/")
        return
    
    # Step 3: Upload to S3
    print("\n☁️ Step 3: Uploading to S3...")
    s3_result = upload_to_s3(dist_dir)
    
    if not s3_result:
        print("\n❌ S3 upload failed")
        return
    
    # Step 4: Setup CloudFront
    print("\n🌐 Step 4: Setting up CloudFront...")
    cf_result = create_cloudfront_distribution(s3_result['bucket'])
    
    # Save outputs
    output = {
        's3': s3_result,
        'cloudfront': cf_result
    }
    
    output_file = Path(__file__).parent.parent / 'frontend-outputs.json'
    with open(output_file, 'w') as f:
        json.dump(output, f, indent=2)
    
    print("\n" + "=" * 60)
    print("✅ Frontend Deployment Complete!")
    print("=" * 60)
    
    print(f"\n📦 S3 Bucket: {s3_result['bucket']}")
    print(f"🔗 S3 URL: {s3_result['url']}")
    
    if cf_result:
        print(f"\n🌐 CloudFront URL: {cf_result['url']}")
        print("   (May take 15-20 minutes to become available globally)")
    
    print(f"\n💾 Outputs saved to: {output_file}")
    
    print("\n" + "=" * 60)
    print("🎉 TRACE AWS Implementation Complete!")
    print("=" * 60)


if __name__ == '__main__':
    main()
